import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import axios from "axios";
import Loader from "@/frontend/components/Loader";

export default function Home() {
  const [prompt, setPrompt] = useState("");
  const [generatedText, setGeneratedText] = useState("");
  const [loader, setLoader] = useState(false);

  const handleSubmit = async (event) => {
    event.preventDefault();
    const model = {
      inputText: prompt,
    };
    try {
      setGeneratedText("");
      setLoader(true);
      const { data } = await axios.post(
        "/api/chatgpt/chatgpt-chatcompletion",
        model
      );
      setLoader(false);
      setGeneratedText(data);
      setPrompt("");
    } catch (error) {
      setLoader(false);
      console.log(error);
    }
  };

  const clearTextHandler = (event) => {
    event.preventDefault();
    setGeneratedText("");
    setPrompt("");
  };

  return (
    <>
      <Head>
        <title>chatgpt - Chat Completion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <>
          <h1 className="text-xl md:text-5xl text-center font-bold py-10 border-b">
            OpenAI GPT Demo - Chat Completion
          </h1>
          <div className="container mx-auto py-3">
            <form onSubmit={handleSubmit}>
              <label htmlFor="prompt" className="text-xl font-bold">
                Enter a prompt:
              </label>
              <br></br>
              <textarea
                className="border px-2 py-2 focus:outline-none rounded-md"
                id="prompt"
                row={10}
                cols={50}
                value={prompt}
                onChange={(event) => setPrompt(event.target.value)}
                required
              />
              <br></br>
              <br></br>
              <button
                type="submit"
                className="bg-green-500 border-green-500 text-yellow-50 px-4 py-2 border rounded-md hover:bg-green-200 hover:text-green-900 focus:outline-none"
              >
                Generate Chat
              </button>
              <button
                onClick={clearTextHandler}
                className="mx-2 bg-red-500 border-red-500 text-yellow-50 px-4 py-2 border rounded-md hover:bg-red-200 hover:text-red-900 focus:outline-none"
              >
                Clear Chat
              </button>
            </form>
            <br></br>
            <br></br>
            {loader ? <Loader /> : <></>}
            {generatedText && (
              <div>
                <h2 className="text-xl font-bold">Generated Chat:</h2>
                <p style={{ textAlign: "justify" }}>
                  {generatedText.generatedChatResponse}
                </p>
              </div>
            )}
          </div>
        </>
      </main>
    </>
  );
}
