import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import axios from "axios";
import Loader from "@/frontend/components/Loader";
import Image from "next/image";

export default function Home() {
  const [imagePath, setImagePath] = useState("");
  const [prompt, setPrompt] = useState("");
  const [generatedText, setGeneratedText] = useState("");
  const [loader, setLoader] = useState(false);

  const handleSubmit = async (event) => {
    event.preventDefault();
    const model = {
      inputText: prompt,
    };
    try {
      setGeneratedText("");
      setLoader(true);
      const { data } = await axios.post(
        "/api/chatgpt/chatgpt-createimage",
        model
      );
      setLoader(false);
      setGeneratedText(data);
      setPrompt("");
    } catch (error) {
      setLoader(false);
      console.log(error);
    }
  };

  const clearTextHandler = (event) => {
    event.preventDefault();
    setGeneratedText("");
    setPrompt("");
  };

  const handleUpload = async (event) => {
    event.preventDefault();
    const formData = new FormData();
    formData.append("image", event.target.image.files[0]);

    const response = await fetch("/api/upload", {
      method: "POST",
      body: formData,
    });
    console.log(response);
    if (response.ok) {
      const { imagePath } = await response.json();
      setImagePath(imagePath);
    } else {
      const { error } = await response.json();
      console.error(error);
    }
  };
  console.log(imagePath);

  return (
    <>
      <Head>
        <title>chatgpt - Create Images Edit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
          integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>
      <main className={styles.main}>
        <>
          <h1 className="text-xl md:text-5xl text-center font-bold py-10 border-b">
            OpenAI GPT Demo - Create Images Edit
          </h1>
          <div className="container mx-auto py-3">
            <form onSubmit={handleSubmit}>
              <label htmlFor="prompt" className="text-xl font-bold">
                Enter a prompt:
              </label>
              <br></br>
              <textarea
                className="border px-2 py-2 focus:outline-none rounded-md"
                id="prompt"
                row={10}
                cols={50}
                value={prompt}
                onChange={(event) => setPrompt(event.target.value)}
                required
              />
              <br></br>

              <br></br>
              <br></br>
              <button
                type="submit"
                className="bg-green-500 border-green-500 text-yellow-50 px-4 py-2 border rounded-md hover:bg-green-200 hover:text-green-900 focus:outline-none"
              >
                Generate Images
              </button>
              <button
                onClick={clearTextHandler}
                className="mx-2 bg-red-500 border-red-500 text-yellow-50 px-4 py-2 border rounded-md hover:bg-red-200 hover:text-red-900 focus:outline-none"
              >
                Clear Images
              </button>
            </form>
            <br></br>
            <form onSubmit={handleUpload}>
              <label htmlFor="prompt" className="text-xl font-bold">
                Upload a PNG Image:
              </label>
              <br></br>
              <input type="file" name="image" accept="image/png" required />
              <button
                type="submit"
                className="bg-green-500 border-green-500 text-yellow-50 px-4 py-2 border rounded-md hover:bg-green-200 hover:text-green-900 focus:outline-none"
              >
                Upload
              </button>
            </form>
            <br></br>
            {imagePath && (
              <>
                <span className="text-xl font-bold">Uploaded Image</span>
                <img src={`/${imagePath}`} alt="Uploaded image" />
              </>
            )}
            <br></br>
            <br></br>
            {loader ? <Loader /> : <></>}
            {generatedText && (
              <div className="py-5 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {generatedText ? (
                  generatedText.generatedImageResponse.map((image, index) => (
                    <div key={index}>
                      <Image
                        src={image.url}
                        alt={prompt}
                        width={200}
                        height={200}
                      />
                    </div>
                  ))
                ) : (
                  <span className="text-xl font-bold">No Images Found.</span>
                )}
              </div>
            )}
          </div>
        </>
      </main>
    </>
  );
}
