import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const textGenerationHandler = () => {
    router.push("/chatgpt/chatgpt-createcompletion");
  };
  return (
    <>
      <Head>
        <title>OPENAI GPT DEMO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>OpenAI GPT Demo</h1>
          <ul>
            <li>
              <div>
                <h3>Text Generation</h3>
                <p>
                  Given a prompt, the model will return one or more predicted
                  completions, and can also return the probabilities of
                  alternative tokens at each position.
                </p>
                <button
                  style={{ padding: "0.5rem" }}
                  className={styles.btn0}
                  onClick={textGenerationHandler}
                >
                  Text Generation
                </button>
              </div>
            </li>
          </ul>
        </div>
      </main>
    </>
  );
}
