import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const textGenerationHandler = () => {
    router.push("/chatgpt/chatgpt-createcompletion");
  };
  const chatCompletionHandler = () => {
    router.push("/chatgpt/chatgpt-chatcompletion");
  };
  const createEditsHandler = () => {
    router.push("/chatgpt/chatgpt-createedits");
  };
  const createImageHandler = () => {
    router.push("/chatgpt/chatgpt-createimage");
  };
  return (
    <>
      <Head>
        <title>OPENAI GPT DEMO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>OpenAI GPT Demo</h1>
          <ul>
            <li>
              <div>
                <h3>Completions</h3>
                <p>
                  Given a prompt, the model will return one or more predicted
                  completions, and can also return the probabilities of
                  alternative tokens at each position.
                </p>
                <button
                  style={{ padding: "0.5rem" }}
                  className={styles.btn0}
                  onClick={textGenerationHandler}
                >
                  Try Completion
                </button>
              </div>
            </li>
            <br></br>
            <li>
              <div>
                <h3>Chat</h3>
                <p>
                  Given a chat conversation, the model will return a chat
                  completion response.
                </p>
                <button
                  style={{ padding: "0.5rem" }}
                  className={styles.btn0}
                  onClick={chatCompletionHandler}
                >
                  Try Chat Completion
                </button>
              </div>
            </li>
            <br></br>
            <li>
              <div>
                <h3>Edits</h3>
                <p>
                  Given a prompt and an instruction, the model will return an
                  edited version of the prompt.
                </p>
                <button
                  style={{ padding: "0.5rem" }}
                  className={styles.btn0}
                  onClick={createEditsHandler}
                >
                  Try Edits
                </button>
              </div>
            </li>
            <br></br>
            <li>
              <div>
                <h3>Images</h3>
                <p>
                  Given a prompt and/or an input image, the model will generate
                  a new image.
                </p>
                <ol style={{ marginLeft: "1rem" }}>
                  <li>
                    <div>
                      <h4>Create Image</h4>
                      <p>
                        Given a prompt and/or an input image, the model will
                        generate a new image.
                      </p>
                      <button
                        style={{ padding: "0.5rem" }}
                        className={styles.btn0}
                        onClick={createImageHandler}
                      >
                        Try Create Image
                      </button>
                    </div>
                  </li>
                </ol>
              </div>
            </li>
          </ul>
        </div>
      </main>
    </>
  );
}
